### ISSUE TITLE
"pull access denied for quizmaster"

### ISSUE THREAD

**Issue by TheNomad11** [nymanjens/quizmaster#6]
I tried to install it with the docker compose option and got this error message:

`pull access denied for quizmaster, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

What am I doing wrong? I am installing it on a VPS Ubuntu 20

**Comment by nymanjens** [comment]
Hi!

I tried it locally, and it seems to work fine. The only thing I can think of is if you were trying to download the image at the moment I was uploading a new one (which I did today). Can you retry?

**Comment by Spenser715** [comment]
I too am getting this issue. It says the image has been removed.

`spenser@server-pc:~/quizmaster$ docker-compose up -d
Pulling app (quizmaster:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling app (quizmaster:)...
ERROR: pull access denied for quizmaster, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
`

**Comment by nymanjens** [comment]
Ah, I see, I was checking `docker run nymanjens/quizmaster:latest bin/server`, but this is about `docker-compose up -d`.

I think I've fixed the issue now:https://github.com/nymanjens/quizmaster/commit/2e1cdd1b823cffad0e1faecb00b30a4af5cba119

**Comment by TheNomad11** [comment]
yes, now it worked! the whole (quite long) process ended nevertheless with an error message:

```
Configuration error: Configuration error[application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
	at play.api.Configuration$.configError(Configuration.scala:156)
	at play.api.Configuration$.load(Configuration.scala:102)
	at play.api.Configuration$.load(Configuration.scala:110)
	at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:113)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:49)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:979)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at play.api.Configuration$.$anonfun$load$5(Configuration.scala:74)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.Configuration$.load(Configuration.scala:70)
	... 5 more
Caused by: com.typesafe.config.ConfigException$IO: application.conf: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	... 12 more
Caused by: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	... 15 more
Oops, cannot start the server.
Configuration error: Configuration error[application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
	at play.api.Configuration$.configError(Configuration.scala:156)
	at play.api.Configuration$.load(Configuration.scala:102)
	at play.api.Configuration$.load(Configuration.scala:110)
	at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:113)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:49)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
	at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
	at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:979)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at play.api.Configuration$.$anonfun$load$5(Configuration.scala:74)
	at scala.Option.getOrElse(Option.scala:121)
	at play.api.Configuration$.load(Configuration.scala:70)
	... 5 more
Caused by: com.typesafe.config.ConfigException$IO: application.conf: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
	at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
	... 12 more
Caused by: java.io.IOException: resource not found on classpath: application.conf
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	... 15 more
```

**Comment by nymanjens** [comment]
Yes, I had that error too after compilation was done on my machine and fixed it in 6c4f318dafc6a28784de882a59d35ce48c2af8bf

**Comment by TheNomad11** [comment]
Yes, now I was able to start Quizmaster, thanks a lot!!

**Comment by TheNomad11** [comment]
Not sure if everything works as expected, though, in the demo often stuck at a question, can't navigate to next question, arrow right and left sometimes have no effect, sometimes it just says "waiting for the next question".

**Comment by nymanjens** [comment]
I tried the quiz UI locally and it all seems to work fine. "Waiting for the next question..." is normal if there is currently no question to be answered. That's done by clicking on the padlock icon and then using the arrows.

Do you think your computer is the bottleneck? I just made some more changes to the Docker setup that reduces the image from 2GB to 350MB, which might help.
